const restaurant = {
    name: 'Hungrezi',
    description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id, rem. Culpa fuga, ab harum dicta inventore nulla vero exercitationem perspiciatis consequatur voluptatum tempore sunt similique, illo aliquam est doloremque molestias.',
    minimumOrderValue: 10,
    deliveryPrice: 1,
    categories: [
        {name: 'favorite Dishes', description: '', image: ''},
        {name: 'Salads', description: 'All salads are prepared with a dressing of choice.', image: 'res/salad-category-header.jpg'},
        {name: 'Wraps', description: '', image: 'res/wraps-category-header.jpg'},
        {name: 'Wrap plate', description: '', image: 'res/wrap-plate-category-header.jpg'},
        {name: 'side dishes', description: '', image: 'res/side-dishes-category-header.jpg'},
        {name: 'soft drinks', description: '', image: 'res/drinks-category-header.jpg'},
    ],
    products: [
        {name: 'Oriental plate', category: 'favorite Dishes', description: 'with falafel, homemade hummus and couscous', price: 8.5},
        {name: 'Fresh Food Wrap Menü', category: 'favorite Dishes', description: '<ul><li>1 Siba Wrap<li>Couscous<li>Greek yogurt with olive oil</ul>', price: 7.5},
        {name: 'Fresh Food Wrap', category: 'favorite Dishes', description: 'with turkey breast, rocket, red oak leaf lettuce, coleslaw, vegetable onions and tomatoes', price: 5.7},
        {name: 'mixed salad', category: 'Salads', description: 'ith carrots, tomatoes, onions, coleslaw, red oak leaf lettuce, corn, iceberg lettuce, banquet lettuce and cucumber', price: 6.5},
        {name: 'Fresh Food Salad', category: 'Salads', description: 'with red oak leaf lettuce, coleslaw, tomatoes, banquet lettuce, pomegranate seeds, orange juice, pomegranate and orange', price: 7.5},
        {name: 'vegetarian Wrap', category: 'Wraps', description: 'with Avocado', price: 5.7},
        {name: 'FreshFood Wrap', category: 'Wraps', description: 'with turkey breast, rocket, red oak leaf lettuce, coleslaw, vegetable onions and tomatoes', price: 5.7},
        {name: 'mix Wrap', category: 'Wraps', description: 'with mix vegies', price: 6.9},
        {name: 'Saffron Wrap', category: 'Wraps', description: 'with saffron chicken, mixed salad and steamed onions', price: 7.5},
        {name: 'Oriental wrap', category: 'Wraps', description: 'with homemade hummus, falafel and mixed salad', price: 6.9},
        {name: 'Vegetarian plate', category: 'Wrap plate', description: 'with Avocado', price: 7.9},
        {name: 'Fresh Food plate', category: 'Wrap plate', description: 'with turkey breast, rocket, red oak leaf lettuce, coleslaw, vegetable onions and tomatoes', price: 7.9},
        {name: 'chicken breasts', category: 'Wrap plate', description: 'with chicken breasts with sauce top of it', price: 9},
        {name: 'saffron plate', category: 'Wrap plate', description: 'with saffron chicken, mixed salad and steamed onions', price: 9.5},
        {name: 'Oriental plate', category: 'Wrap plate', description: 'with homemade hummus, falafel and mixed salad', price: 8.5},
        {name: 'Belgian fries', category: 'side dishes', description: '', price: 2.9},
        {name: 'Sweet potato fries', category: 'side dishes', description: '', price: 3.9},
        {name: 'Homemade sauce', category: 'side dishes', description: '', price: 0.7},
        {name: 'Orange juice 0.4l', category: 'soft drinks', description: '', price: 3.5},
        {name: 'Pomegranate juice 0.3l', category: 'soft drinks', description: '', price: 3.9},
        {name: 'Capri Sun 0.2l', category: 'soft drinks', description: '', price: 1},
    ]
}